#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.jellyfin_url = "test"
    args.jellyfin_api_key = "test"
    args.jellyfin_username = "test"
    args.jellyfin_password = "test"
    args.jellyfin_port = "1234"
    args.jellyseerr_url = "test"
    args.jellyseerr_api_key = "test"
    args.jellyseerr_port = "1234"
    args.jellystat_url = "test"
    args.jellystat_api_key = "test"
    args.jellystat_port = "1234"
    args.radarr_url = "test"
    args.radarr_api_key = "test"
    args.radarr_port = "1234"
    args.sonarr_url = "test"
    args.sonarr_api_key = "test"
    args.sonarr_port = "1234"
    args.leaving_soon_dir = "/home/yunohost.multimedia/share/leavingsoon"
    args.media_server_leaving_soon_dir = "/home/yunohost.multimedia/share/leavingsoon"
    args.free_space_check_dir = "/"
    args.dry_run = "true"
    args.whole_tv_show = "false"
    args.whole_show_seeding_check = "false"
    args.leaving_soon = "14d"
    args.expiration_date = "120d"
    args.exclusion_tag = "janitorr_keep"
    args.jellyfin_usage = "false"
    args.jellystat_usage = "false"
    args.jellyseerr_usage = "false"
    args.radarr_usage = "false"
    args.sonarr_usage = "false"
    args.streamystats_usage = "false"
    args.streamystats_url = "test"
    args.streamystats_api_key = "test"
    args.branch_select = "testing"

    exclude = ["install.subdir", "install.multi, install.private, change_url"]
